name: test
on: push
jobs:
  init:
    runs-on: self-hosted
    steps:
       - name: run
         run: |
          sudo bash -c 'echo "<h1> am a developer and same as Devops Engineer </h1>" > /var/www/html/index.html'

